repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: 'v3.4.0'
        hooks:
            -   id: check-added-large-files
            -   id: check-ast
            -   id: check-json
            -   id: double-quote-string-fixer
            -   id: name-tests-test
            -   id: pretty-format-json
                args: [--autofix, --no-sort-keys]
            -   id: requirements-txt-fixer
            -   id: trailing-whitespace
    -   repo: https://github.com/PyCQA/flake8
        rev: '3.9.1'
        hooks:
            -   id: flake8